/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void libraryCanAddTwoAndThree() {
    	Library classUnderTest = new Library();
    	assertEquals(5, classUnderTest.simpleAdd(2, 3));
    	assertEquals(5, classUnderTest.simpleAdd(3, 2));
    }
}
