/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return sdf;
    }

	public int simpleAdd(int i, int j) {
		return i + j;
	}
}
